In [1]:
import pandas as pd
import numpy as np
import torch 
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import DataLoader, Dataset
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.metrics import classification_report
from sklearn.compose import ColumnTransformer

In [2]:
device = ('cuda' if torch.cuda.is_available() else 'cpu')
device

'cuda'

In [3]:
df = pd.read_csv("C:/AEGIS/roadmap/Deep_Learning/customer_churn/data/Churn_Modelling.csv")
df

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,15606229,Obijiaku,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,Johnstone,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,Liu,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,Sabbatini,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,Walker,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [4]:
df.shape

(10000, 14)

In [5]:
df = df.drop(columns = ['Surname', 'RowNumber', 'CustomerId'])
df

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...
9995,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   CreditScore      10000 non-null  int64
 1   Geography        10000 non-null  str
 2   Gender           10000 non-null  str
 3   Age              10000 non-null  int64
 4   Tenure           10000 non-null  int64
 5   Balance          10000 non-null  float64
 6   NumOfProducts    10000 non-null  int64
 7   HasCrCard        10000 non-null  int64
 8   IsActiveMember   10000 non-null  int64
 9   EstimatedSalary  10000 non-null  float64
 10  Exited           10000 non-null  int64
dtypes: float64(2), int64(7), str(2)
memory usage: 859.5 KB

In [7]:
X = df.drop(columns='Exited')
y = df['Exited'].values

In [8]:
num_cols = X.select_dtypes(include='number').columns.tolist()
num_cols

['CreditScore',
 'Age',
 'Tenure',
 'Balance',
 'NumOfProducts',
 'HasCrCard',
 'IsActiveMember',
 'EstimatedSalary']

In [9]:
cat_cols = X.select_dtypes(include='str').columns.tolist()
cat_cols

['Geography', 'Gender']

In [10]:
preprocessor = ColumnTransformer([
    ('scale', StandardScaler(), num_cols),
    ('ohe', OneHotEncoder(sparse_output=False, drop='first'), cat_cols)
], remainder='passthrough')

In [11]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 42)

In [12]:
X_train = preprocessor.fit_transform(X_train)
X_test = preprocessor.transform(X_test)

In [13]:
class CustomDataset(Dataset):
    def __init__(self, features, labels):
        self.features = torch.tensor(features, dtype=torch.float32)
        self.labels = torch.tensor(labels, dtype = torch.long)

    def __len__(self):
        return len(self.features)

    def __getitem__(self, index):
        return self.features[index], self.labels[index]

In [14]:
train_dataset = CustomDataset(X_train, y_train)
test_dataset = CustomDataset(X_test, y_test)

In [15]:
X_train.shape[0]

8000

In [16]:
X_train.shape[1]

11

In [17]:
len(train_dataset)

8000

In [18]:
train_loader = DataLoader(train_dataset, batch_size = 1000, shuffle = True, pin_memory=True)
test_loader = DataLoader(test_dataset, batch_size= 1000, shuffle=False, pin_memory=True)

In [19]:
class ANN(nn.Module):
    def __init__(self, input_dim, output_dim):
        super().__init__()

        self.model = nn.Sequential(
            nn.Linear(input_dim, 5),
            nn.ReLU(),
            nn.Linear(5, 3),
            nn.ReLU(),
            nn.Linear(3,output_dim)
        )

    def forward(self, x):
        return self.model(x)

In [20]:
learning_rate = 0.5
epochs = 100

In [21]:
model = ANN(X_train.shape[1], 2)
model = model.to(device)

criterion = nn.CrossEntropyLoss()

optimizer = optim.SGD(model.parameters(), lr = learning_rate)

In [22]:
for epoch in range(epochs):
    total_epoch_loss = 0
    for batch_features, batch_labels in train_loader:
        batch_features, batch_labels = batch_features.to(device), batch_labels.to(device)
        outputs = model(batch_features)
        loss = criterion(outputs , batch_labels)
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()
        total_epoch_loss += loss.item()
    avg_loss = total_epoch_loss / len(train_loader)
    print(f"Epoch {epoch + 1} : Loss {avg_loss}")

Epoch 1 : Loss 0.5590362809598446
Epoch 2 : Loss 0.5032815858721733
Epoch 3 : Loss 0.4959247224032879
Epoch 4 : Loss 0.4860699437558651
Epoch 5 : Loss 0.47574392706155777
Epoch 6 : Loss 0.4649530500173569
Epoch 7 : Loss 0.45424820110201836
Epoch 8 : Loss 0.4449317716062069
Epoch 9 : Loss 0.43613941222429276
Epoch 10 : Loss 0.42890722304582596
Epoch 11 : Loss 0.4218587651848793
Epoch 12 : Loss 0.415602121502161
Epoch 13 : Loss 0.40883251279592514
Epoch 14 : Loss 0.40160205587744713
Epoch 15 : Loss 0.39438943937420845
Epoch 16 : Loss 0.38902772590518
Epoch 17 : Loss 0.3833119161427021
Epoch 18 : Loss 0.37774229794740677
Epoch 19 : Loss 0.3735411688685417
Epoch 20 : Loss 0.370404876768589
Epoch 21 : Loss 0.3660259246826172
Epoch 22 : Loss 0.36189479753375053
Epoch 23 : Loss 0.35907330736517906
Epoch 24 : Loss 0.35873936489224434
Epoch 25 : Loss 0.35641423240303993
Epoch 26 : Loss 0.3546576164662838
Epoch 27 : Loss 0.35258759185671806
Epoch 28 : Loss 0.3509293459355831
Epoch 29 : Loss 0.3552659824490547
Epoch 30 : Loss 0.35642294958233833
Epoch 31 : Loss 0.3480708487331867
Epoch 32 : Loss 0.36093396320939064
Epoch 33 : Loss 0.35384057462215424
Epoch 34 : Loss 0.345843568444252
Epoch 35 : Loss 0.36517638713121414
Epoch 36 : Loss 0.35071590170264244
Epoch 37 : Loss 0.3494545817375183
Epoch 38 : Loss 0.3475235626101494
Epoch 39 : Loss 0.3494095243513584
Epoch 40 : Loss 0.3633655942976475
Epoch 41 : Loss 0.34474578872323036
Epoch 42 : Loss 0.34681230410933495
Epoch 43 : Loss 0.3442640155553818
Epoch 44 : Loss 0.34455057606101036
Epoch 45 : Loss 0.3427528962492943
Epoch 46 : Loss 0.34829628467559814
Epoch 47 : Loss 0.3425784036517143
Epoch 48 : Loss 0.35172175616025925
Epoch 49 : Loss 0.354866586625576
Epoch 50 : Loss 0.34483302757143974
Epoch 51 : Loss 0.3418966978788376
Epoch 52 : Loss 0.3433472253382206
Epoch 53 : Loss 0.3456112705171108
Epoch 54 : Loss 0.3552929125726223
Epoch 55 : Loss 0.34248068928718567
Epoch 56 : Loss 0.3452202379703522
Epoch 57 : Loss 0.3506897762417793
Epoch 58 : Loss 0.3435557596385479
Epoch 59 : Loss 0.3425792083144188
Epoch 60 : Loss 0.34177877753973007
Epoch 61 : Loss 0.34238816797733307
Epoch 62 : Loss 0.34971772134304047
Epoch 63 : Loss 0.3411436378955841
Epoch 64 : Loss 0.3406244218349457
Epoch 65 : Loss 0.3427831418812275
Epoch 66 : Loss 0.3426876962184906
Epoch 67 : Loss 0.3421017900109291
Epoch 68 : Loss 0.34008172154426575
Epoch 69 : Loss 0.3420840688049793
Epoch 70 : Loss 0.33887317404150963
Epoch 71 : Loss 0.3415752500295639
Epoch 72 : Loss 0.33976704627275467
Epoch 73 : Loss 0.3461502604186535
Epoch 74 : Loss 0.36539850756525993
Epoch 75 : Loss 0.3447874076664448
Epoch 76 : Loss 0.34103192016482353
Epoch 77 : Loss 0.3400196433067322
Epoch 78 : Loss 0.3397270515561104
Epoch 79 : Loss 0.34778671339154243
Epoch 80 : Loss 0.34119388088583946
Epoch 81 : Loss 0.33990104496479034
Epoch 82 : Loss 0.341156680136919
Epoch 83 : Loss 0.3553353548049927
Epoch 84 : Loss 0.3421298898756504
Epoch 85 : Loss 0.33934247866272926
Epoch 86 : Loss 0.3398279696702957
Epoch 87 : Loss 0.34225330874323845
Epoch 88 : Loss 0.339585617184639
Epoch 89 : Loss 0.3384850285947323
Epoch 90 : Loss 0.33932749554514885
Epoch 91 : Loss 0.3381041958928108
Epoch 92 : Loss 0.33832503482699394
Epoch 93 : Loss 0.3382905386388302
Epoch 94 : Loss 0.3395330458879471
Epoch 95 : Loss 0.34181715175509453
Epoch 96 : Loss 0.33799199014902115
Epoch 97 : Loss 0.33969995751976967
Epoch 98 : Loss 0.3548445627093315
Epoch 99 : Loss 0.3415589928627014
Epoch 100 : Loss 0.3466702476143837

In [23]:
model.eval()

ANN(
  (model): Sequential(
    (0): Linear(in_features=11, out_features=5, bias=True)
    (1): ReLU()
    (2): Linear(in_features=5, out_features=3, bias=True)
    (3): ReLU()
    (4): Linear(in_features=3, out_features=2, bias=True)
  )
)

In [24]:
y_preds = []
y_true = []
with torch.no_grad():
    for batch_features, batch_labels in test_loader:
        batch_features = batch_features.to(device)
        outputs = model(batch_features)
        preds = torch.argmax(outputs, dim=1)
        y_preds.extend(preds.cpu().numpy())
        y_true.extend(batch_labels.numpy())

print(classification_report(y_true, y_preds))

              precision    recall  f1-score   support

           0       0.89      0.95      0.92      1607
           1       0.70      0.52      0.60       393

    accuracy                           0.86      2000
   macro avg       0.80      0.73      0.76      2000
weighted avg       0.85      0.86      0.85      2000